# name: Generate Datas

# on:
#   schedule: # execute every 12 hours
#     - cron: "* */12 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     name: Jobs to update datas
#     runs-on: ubuntu-latest
#     steps:
#       # Snake Animation
#       - uses: Platane/snk@master
#         id: snake-gif
#         with:
#           github_user_name: GiangHLe
#           svg_out_path: dist/github-contribution-grid-snake.svg

#       - uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


name: main

on:
  schedule: 
    - cron: "* */12 * * *"

jobs:
  test-action-svg-only:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - run: yarn install --frozen-lockfile

      - name: build svg-only action
        run: |
          npm run build:action
          rm -r svg-only/dist
          mv packages/action/dist svg-only/dist

      - name: generate-snake-game-from-github-contribution-grid
        id: generate-snake
        uses: ./svg-only
        with:
          github_user_name: GiangHLe
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ensure the generated file exists
        run: |
          ls dist
          test -f dist/github-contribution-grid-snake.svg
          test -f dist/github-contribution-grid-snake-dark.svg

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-svg-only
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
